version: '3.7'
services:
  discord-bot:
    container_name: discord-bot
    image: cedricmeyer/node-web-app:latest
    restart: unless-stopped
    volumes:
      - ${CONFIG}/discord-bot/db:/usr/src/app/db
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
